<?php
/*
Plugin Name: Hero Slider
Description: Vídeo and Image Slider
*/

/* ==================================================
    IMAGE SLIDER - POST TYPE
================================================== */

add_action('init', 'create_post_type');

function create_post_type()
{
    register_post_type('image_slider',
    array(
      'labels' => array(
        'name' => __('Image Slider'),
        'singular_name' => __('Slide')
      ),
      'public' => true,
      'has_archive' => true,
      'show_in_rest' => true,
      'supports' => array('title', 'thumbnail'),
      'menu_icon' => 'dashicons-money',
    )
  );
}

/* ==================================================
    MOVIE SLIDER - MENU
================================================== */

add_action('admin_menu', 'register_movie_slider_menu_page');

function register_movie_slider_menu_page()
{
    add_menu_page(
        'Movie Slider',  // page_title
        'Movie Slider',  // menu_title
        'manage_options',// capability
        'movie_slider',  // menu_slug
        'render_movie_slider_menu_page', // function
        'dashicons-format-video',
        6
    );
}

function render_movie_slider_menu_page()
{
    ?>
  <form action='options.php' method='post' enctype="multipart/form-data">

    <h1>Movie Slider</h1>

    <?php
    settings_fields('MovieSlider_Options');
    do_settings_sections('MovieSlider_Options');
    submit_button(); ?>

  </form>
  <?php
}

add_action('admin_init', 'movie_slider_settings_init');

function movie_slider_settings_init(){
  register_setting('MovieSlider_Options', 'movie_slider_settings');

  // DEFAULT SECTION
  // ==================================================
  add_settings_section(
    'movie_slider_default_section',
    __('Default Options', 'wordpress'),
    'movie_slider_settings_section_callback',
    'MovieSlider_Options'
  );

  // Checkbox field
  add_settings_field(
    'movie_slider_checkbox',
    __('Use Movie Slider?'),
    'movie_slider_checkbox_render',
    'MovieSlider_Options',
    'movie_slider_default_section'
  );

  // Movie URL field
  add_settings_field(
    'movie_slider_movieurl',
    __('Movie URL:'),
    'movie_slider_movieurl_display',
    'MovieSlider_Options',
    'movie_slider_default_section'
  );

  // CAPTION SECTION
  // ==================================================

  add_settings_section(
    'movie_slider_caption_section',
    __('Caption Options', 'wordpress'),
    'movie_slider_settings_section_callback',
    'MovieSlider_Options'
  );

  // Caption field
  add_settings_field(
    'movie_slider_text_field_1',
    __('Caption', 'wordpress'),
    'movie_slider_text_field_1_render',
    'MovieSlider_Options',
    'movie_slider_caption_section'
  );

  // Dynamic field
  for ($n_fields=0; $n_fields < 10; $n_fields++) {
    add_settings_field(
      'movie_slider_text_field_'.$n_fields,
      __('Caption', 'wordpress'),
      'movie_slider_text_field_render',
      'MovieSlider_Options',
      'movie_slider_caption_section',
      array('number' => $n_fields)
    );
  }
}

// Checkbox field
function movie_slider_checkbox_render()
{
    $options = get_option('movie_slider_settings'); ?>
<div id="checkbox-wrapper">
  <span>No</span>
  <input type='checkbox' id='movie_slider_settings[movie_slider_checkbox_field_0]' class='switch-toggle' name='movie_slider_settings[movie_slider_checkbox_field_0]' <?php checked($options['movie_slider_checkbox_field_0'], 1); ?> value='1'>
  <label for="movie_slider_settings[movie_slider_checkbox_field_0]"></label>
  <span>Yes</span>
</div>
<?php
}

// Movie URL field
function movie_slider_movieurl_display()
{
    $options = get_option('movie_slider_settings'); ?>
  <input type='file' name='movie_slider_settings[movie_slider_movieurl]' value='<?php echo $options['movie_slider_movieurl']; ?>'>
  <?php
}

// Caption field
function movie_slider_text_field_1_render()
{
    $options = get_option('movie_slider_settings'); ?>
<input type='text' name='movie_slider_settings[movie_slider_text_field_1]' value='<?php echo $options['movie_slider_text_field_1']; ?>'>
<hr />
<?php
}

// Default field
function movie_slider_text_field_render($args)
{
    $options = get_option('movie_slider_settings'); ?>
    <p>
      args: <?php echo $args['number'] ?>
    </p>
<input type='text' name='movie_slider_settings[movie_slider_text_field_<?php echo $args['number'] ?>]' value='<?php echo $options['movie_slider_text_field_<?php $args ?>']; ?>'>
<hr />
<?php
}


function movie_slider_settings_section_callback()
{
    echo __('This section description', 'wordpress');
}

/* =====

===== */

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

 add_action('add_meta_boxes', 'animacao_add_meta_box');

 function animacao_add_meta_box()
 {
     add_meta_box(
        'animao-animao',
        __('Animação', 'animao'),
        'animacao_html',
        'image_slider',
        'normal',
        'default'
    );
 }

 function animacao_html($post)
 {
     wp_nonce_field('_animacao_nonce', 'animacao_nonce'); ?>

 	<p>
 		<label for="animacao_transion"><?php _e('Transição', 'animao'); ?></label><br>
 		<select name="animacao_transion" id="animacao_transion">
 			<option <?php echo (animacao_get_meta('animacao_transion') === 'type_1') ? 'selected' : '' ?>>type_1</option>
 			<option <?php echo (animacao_get_meta('animacao_transion') === 'type_2') ? 'selected' : '' ?>>type_2</option>
 			<option <?php echo (animacao_get_meta('animacao_transion') === 'type_3') ? 'selected' : '' ?>>type_3</option>
 			<option <?php echo (animacao_get_meta('animacao_transion') === 'type_4') ? 'selected' : '' ?>>type_4</option>
 			<option <?php echo (animacao_get_meta('animacao_transion') === 'type_5') ? 'selected' : '' ?>>type_5</option>
 		</select>
 	</p><?php
 }

function animacao_get_meta($value)
{
    global $post;

    $field = get_post_meta($post->ID, $value, true);
    if (! empty($field)) {
        return is_array($field) ? stripslashes_deep($field) : stripslashes(wp_kses_decode_entities($field));
    } else {
        return false;
    }
}

add_action('save_post', 'animacao_save');

function animacao_save($post_id)
{
    if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
        return;
    }
    if (! isset($_POST['animacao_nonce']) || ! wp_verify_nonce($_POST['animacao_nonce'], '_animacao_nonce')) {
        return;
    }
    if (! current_user_can('edit_post', $post_id)) {
        return;
    }

    if (isset($_POST['animacao_transion'])) {
        update_post_meta($post_id, 'animacao_transion', esc_attr($_POST['animacao_transion']));
    }
}

/*
    Usage: animacao_get_meta( 'animacao_transion' )
*/

/* ==========
	STYLES - TOGGLE SWITCH
========== */

// load css into the admin pages
function mytheme_enqueue_options_style() {
  wp_enqueue_style( 'mytheme-options-style', plugins_url() . '/hero-slider/styles/admin-slider.css' ); 
}

add_action( 'admin_enqueue_scripts', 'mytheme_enqueue_options_style' );
?>
